### ISSUE TITLE
doesn't seems to work with the latest version (1.0.2) and it's updated dependcies

### ISSUE THREAD

**Issue by roeycohen** [mafintosh/torrent-memory-storage#1]
just running the sample code returns this error:

```
Error: First argument must be abstract-chunk-store compliant
    at new ImmediateStore (...\node_modules\torrent-stream\node_modules\immediate-chunk-store\index.js:10:11)
    at ImmediateStore (...\node_modules\torrent-stream\node_modules\immediate-chunk-store\index.js:4:49)
    at ontorrent (...\node_modules\torrent-stream\index.js:130:20)
    at ...\node_modules\torrent-stream\index.js:626:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by roeycohen** [comment]
ok, i understand that this module is not maintained anymore.
use this instead: https://www.npmjs.com/package/memory-chunk-store

**Comment by mafintosh** [comment]
ah yes we changed torrent-stream to use abstract-chunk-store, https://github.com/mafintosh/abstract-chunk-store

basically any storage provider on that list will work (there is a memory one as well)

**Comment by mafintosh** [comment]
... i should mention that in the readme

**Comment by roeycohen** [comment]
you've precede me by 4 seconds!!
